-- Supabase SQL Editor にそのまま貼り付けて実行してください。
create table if not exists posts (
  id bigint generated by default as identity primary key,
  author text not null,
  title text not null,
  description text not null,
  tags text[] default '{}',
  file_url text,
  external_url text,
  created_at timestamptz not null default now(),
  constraint post_source_check check (
    (file_url is not null and external_url is null)
    or (file_url is null and external_url is not null)
  )
);

create table if not exists comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  author text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table posts enable row level security;
alter table comments enable row level security;

create policy "posts public read" on posts for select using (true);
create policy "posts public insert" on posts for insert with check (true);
create policy "comments public read" on comments for select using (true);
create policy "comments public insert" on comments for insert with check (true);

insert into storage.buckets (id,name,public) values ('documents','documents',true)
on conflict (id) do nothing;

create policy "documents public read" on storage.objects
for select using (bucket_id = 'documents');
create policy "documents public upload" on storage.objects
for insert with check (bucket_id = 'documents');
